kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1-mariadb
  labels:
    name: pvc1-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: pv1-mariadb