kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1-mariadb
  labels:
    name: pv1-mariadb
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mariadb"
    type: DirectoryOrCreate