apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbootapp
  name: springbootapp
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
      targetPort: 8080
      protocol: TCP
  selector:
    app: springbootapp